(function(){'use strict';var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))break a;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&r(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(h||"")+"_"+d++,h)}function c(h,f){this.g=h;r(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=t[b[c]];typeof e==="function"&&typeof e.prototype[a]!="function"&&r(e.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var da=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.N=b.prototype}function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function la(a){return ma(a,a)}
function ma(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function na(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.o=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}na.prototype.m=function(a){this.i=a};function pa(a,b){a.j={S:b,U:!0};a.g=a.o}na.prototype.return=function(a){this.j={return:a};this.g=this.o};function y(a,b,c){a.g=c;return{value:b}}function qa(a){this.g=new na;this.h=a}
function ra(a,b){oa(a.g);var c=a.g.h;if(c)return sa(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.g.return);a.g.return(b);return A(a)}function sa(a,b,c,e){try{var d=b.call(a.g.h,c);if(!(d instanceof Object))throw new TypeError("Iterator result "+d+" is not an object");if(!d.done)return a.g.l=!1,d;var h=d.value}catch(f){return a.g.h=null,pa(a.g,f),A(a)}a.g.h=null;e.call(a.g,h);return A(a)}
function A(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,pa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.U)throw b.S;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=A(a));return b};this.throw=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h["throw"],b,a.g.m):(pa(a.g,b),b=A(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,d){function h(f){f.done?e(f.value):Promise.resolve(f.value).then(b,c).then(h,d)}h(a.next())})}
function B(a){return ua(new ta(new qa(a)))}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}u("globalThis",function(a){return a||t});
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.o=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function e(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var d=t.setTimeout;c.prototype.i=function(f){d(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.C),reject:f(this.l)}};b.prototype.C=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.F(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.B(f):this.m(f)}};
b.prototype.B=function(f){var g=void 0;try{g=f.then}catch(k){this.l(k);return}typeof g=="function"?this.I(g,f):this.m(f)};b.prototype.l=function(f){this.v(2,f)};b.prototype.m=function(f){this.v(1,f)};b.prototype.v=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.i=g;this.h===2&&this.D();this.H()};b.prototype.D=function(){var f=this;d(function(){if(f.A()){var g=t.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.A=
function(){if(this.o)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.H=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;b.prototype.F=
function(f){var g=this.j();f.J(g.resolve,g.reject)};b.prototype.I=function(f,g){var k=this.j();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(q,x){return typeof q=="function"?function(z){try{l(q(z))}catch(w){m(w)}}:x}var l,m,n=new b(function(q,x){l=q;m=x});this.J(k(f,l),k(g,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.J=function(f,g){function k(){switch(l.h){case 1:f(l.i);break;case 2:g(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?h.h(k):this.g.push(k);this.o=!0};b.resolve=e;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=v(f),m=l.next();!m.done;m=l.next())e(m.value).J(g,k)})};b.all=function(f){var g=v(f),k=g.next();return k.done?e([]):new b(function(l,m){function n(z){return function(w){q[z]=w;x--;x==0&&l(q)}}var q=[],x=0;do q.push(void 0),x++,e(k.value).J(n(q.length-1),m),k=g.next();while(!k.done)})};return b});
function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)}u("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var e=this;e instanceof String&&(e=String(e));for(var d=e.length,h=0;h<d;h++){var f=e[h];if(b.call(c,f,h,e)){b=f;break a}}b=void 0}return b}});
u("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function e(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function d(k){if(!C(k,f)){var l=new c;r(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!e(k))throw Error("Invalid WeakMap key");d(k);if(!C(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return e(k)&&C(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return e(k)&&C(k,
f)&&C(k[f],this.g)};b.prototype.delete=function(k){return e(k)&&C(k,f)&&C(k[f],this.g)?delete k[f][this.g]:!1};return b});
u("Map",function(a){function b(){var g={};return g.u=g.next=g.head=g}function c(g,k){var l=g[1];return ca(function(){if(l){for(;l.head!=g[1];)l=l.u;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function e(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&C(g[0],l))for(g=0;g<m.length;g++){var n=m[g];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:g,entry:n}}return{id:l,
list:m,index:-1,entry:void 0}}function d(g){this[0]={};this[1]=b();this.size=0;if(g){g=v(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(v([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(n){return!1}}())return a;var h=new WeakMap;d.prototype.set=function(g,k){g=g===0?0:g;var l=e(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],u:this[1].u,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].u.next=l.entry,this[1].u=l.entry,this.size++);return this};d.prototype.delete=function(g){g=e(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.u.next=g.entry.next,
g.entry.next.u=g.entry.u,g.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].u=b();this.size=0};d.prototype.has=function(g){return!!e(this,g).entry};d.prototype.get=function(g){return(g=e(this,g).entry)&&g.value};d.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};d.prototype.keys=function(){return c(this,function(g){return g.key})};d.prototype.values=function(){return c(this,function(g){return g.value})};d.prototype.forEach=
function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(k,m[1],m[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var f=0;return d});u("Array.from",function(a){return a?a:function(b,c,e){c=c!=null?c:function(g){return g};var d=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)d.push(c.call(e,h.value,f++))}else for(h=b.length,f=0;f<h;f++)d.push(c.call(e,b[f],f));return d}});
u("Object.entries",function(a){return a?a:function(b){var c=[],e;for(e in b)C(b,e)&&c.push([e,b[e]]);return c}});u("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});u("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});u("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
u("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var d=e.length;c=c||0;for(c<0&&(c=Math.max(c+d,0));c<d;c++){var h=e[c];if(h===b||Object.is(h,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});
function wa(a,b){a instanceof String&&(a+="");var c=0,e=!1,d={next:function(){if(!e&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}e=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d}u("Array.prototype.entries",function(a){return a?a:function(){return wa(this,function(b,c){return[b,c]})}});u("Object.values",function(a){return a?a:function(b){var c=[],e;for(e in b)C(b,e)&&c.push(b[e]);return c}});
u("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});u("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});u("Array.prototype.values",function(a){return a?a:function(){return wa(this,function(b,c){return c})}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var xa=xa||{},D=this||self;function ya(a,b){var c=za("CLOSURE_FLAGS");a=c&&c[a];return a!=null?a:b}function za(a,b){a=a.split(".");b=b||D;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function Aa(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function Ba(a){var b=Aa(a);return b=="array"||b=="object"&&typeof a.length=="number"}function E(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function Ca(a,b,c){return a.call.apply(a.bind,arguments)}function Da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function Ea(a,b,c){Ea=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Ca:Da;return Ea.apply(null,arguments)}
function Fa(a,b){function c(){}c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ka=function(e,d,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[d].apply(e,f)}};var Ga;function Ha(a){D.setTimeout(function(){throw a;},0)};var Ia=ya(748402147,ya(1,!0));function Ja(){var a=D.navigator;return a&&(a=a.userAgent)?a:""};var Ka=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},La=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,e=typeof a==="string"?a.split(""):a,d=0;d<c;d++)d in e&&b.call(void 0,e[d],d,a)};
function Ma(a,b){b=Ka(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Na(a){var b=a.length;if(b>0){for(var c=Array(b),e=0;e<b;e++)c[e]=a[e];return c}return[]};var Oa=Ja().toLowerCase().indexOf("webkit")!=-1&&Ja().indexOf("Edge")==-1&&Ja().indexOf("Mobile")!=-1;var Pa=typeof D.BigInt==="function"&&typeof D.BigInt(0)==="bigint";var Qa=Number.MIN_SAFE_INTEGER.toString(),Ra=Pa?BigInt(Number.MIN_SAFE_INTEGER):void 0,Sa=Number.MAX_SAFE_INTEGER.toString(),Ta=Pa?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Ua(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var e=a[c],d=b[c];if(e>d)return!1;if(e<d)return!0}};var Va=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Wa(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Xa=Wa("jas",void 0,!0),Ya=Wa(void 0,"0actk"),F=Wa("m_m","la",!0);var Za=Math.max,$a=Za.apply,ab=Object.values({ea:1,da:2,ca:4,ha:8,ja:16,fa:32,X:64,aa:128,Y:256,ia:512,Z:1024,ba:2048,ga:4096}),bb;if(ab instanceof Array)bb=ab;else{for(var cb=v(ab),db,eb=[];!(db=cb.next()).done;)eb.push(db.value);bb=eb}$a.call(Za,Math,bb);var fb={T:{value:0,configurable:!0,writable:!0,enumerable:!1}},gb=Object.defineProperties,G=Va?Xa:"T";function hb(a,b){Va||G in a||gb(a,fb);a[G]|=b}function H(a,b){Va||G in a||gb(a,fb);a[G]=b};var I={};function J(a,b){return b===void 0?a.h!==K&&!!(2&(a.g[G]|0)):!!(2&b)&&a.h!==K}var K={};var ib=void 0;function jb(a){return a.displayName||a.name||"unknown type name"};function kb(a){return a};function lb(a,b,c,e){var d=e!==void 0;e=!!e;var h=[],f=a.length,g=4294967295,k=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var n=f&&a[f-1];n!=null&&typeof n==="object"&&n.constructor===Object?(f--,g=f):n=void 0;if(l&&!(b&128)&&!d){k=!0;var q;g=((q=mb)!=null?q:kb)(g-m,m,a,n,void 0)+m}}b=void 0;for(d=0;d<f;d++)if(q=a[d],q!=null&&(q=c(q,e))!=null)if(l&&d>=g){var x=d-m,z=void 0;((z=b)!=null?z:b={})[x]=q}else h[d]=q;if(n)for(var w in n)a=n[w],a!=null&&(a=c(a,e))!=null&&(f=+w,d=void 0,l&&!Number.isNaN(f)&&
(d=f+m)<g?h[d]=a:(f=void 0,((f=b)!=null?f:b={})[w]=a));b&&(k?h.push(b):h[g]=b);return h}function nb(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Pa?a>=Ra&&a<=Ta:a[0]==="-"?Ua(a,Qa):Ua(a,Sa))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[G]|0;return a.length===0&&b&1?void 0:lb(a,b,nb)}if(a!=null&&a[F]===I)return ob(a);return}return a}var mb;function ob(a){a=a.g;return lb(a,a[G]|0,nb)};function pb(a,b,c){var e=e===void 0?0:e;if(a==null){var d=32;c?(a=[c],d|=128):a=[];b&&(d=d&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");d=a[G]|0;if(Ia&&1&d)throw Error("rfarr");2048&d&&!(2&d)&&qb();if(d&256)throw Error("farr");if(d&64)return e!==0||d&2048||H(a,d|2048),a;if(c&&(d|=128,c!==a[0]))throw Error("mid");a:{c=a;d|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=d&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=
+k,h<f&&(c[h+b]=g[k],delete g[k]);d=d&-8380417|(f&1023)<<13;break a}}if(b){k=Math.max(b,h-(d&128?0:-1));if(k>1024)throw Error("spvt");d=d&-8380417|(k&1023)<<13}}}d|=64;e===0&&(d|=2048);H(a,d);return a}function qb(){if(Ia)throw Error("carr");if(Ya!=null){var a;var b=(a=ib)!=null?a:ib={};a=b[Ya]||0;a>=5||(b[Ya]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",Ha(b))}};function rb(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[G]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=L(a,c,!1,b&&!(c&16)):(hb(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[F]===I)return b=a.g,c=b[G]|0,J(a,c)?a:sb(a,b,c)?tb(a,b):L(b,c)}function tb(a,b,c){a=new a.constructor(b);c&&(a.h=K);a.i=K;return a}function L(a,b,c,e){e!=null||(e=!!(34&b));a=lb(a,b,rb,e);e=32;c&&(e|=2);b=b&8380609|e;H(a,b);return a}
function ub(a){if(a.h!==K)return!1;var b=a.g;b=L(b,b[G]|0);hb(b,2048);a.g=b;a.h=void 0;a.i=void 0;return!0}function vb(a){if(!ub(a)&&J(a,a.g[G]|0))throw Error();}function wb(a,b){b===void 0&&(b=a[G]|0);b&32&&!(b&4096)&&H(a,b|4096)}function sb(a,b,c){return c&2?!0:c&32&&!(c&4096)?(H(b,c|2),a.h=K,!0):!1};function xb(a,b,c){if(b===-1)return null;var e=b+-1,d=a.length-1;if(!(d<0)){if(e>=d){var h=a[d];if(h!=null&&typeof h==="object"&&h.constructor===Object){d=h[b];var f=!0}else if(e===d)d=h;else return}else d=a[e];if(c&&d!=null){c=c(d);if(c==null)return c;if(!Object.is(c,d))return f?h[b]=c:a[e]=c,c}return d}}
function yb(a,b,c,e){var d=c+-1,h=a.length-1;if(h>=0&&d>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=e,b}if(d<=h)return a[d]=e,b;if(e!==void 0){var g;h=((g=b)!=null?g:b=a[G]|0)>>13&1023||536870912;c>=h?e!=null&&(d={},a[h+-1]=(d[c]=e,d)):a[d]=e}return b}
function zb(a,b){var c=M,e=!1,d=xb(a,1,function(h){if(h!=null&&h[F]===I)var f=h;else if(Array.isArray(h)){f=h[G]|0;var g=f|b&32;g|=b&2;g!==f&&H(h,g);f=new c(h)}else f=void 0;e=f!==h&&f!=null;return f});if(d!=null)return e&&!J(d)&&wb(a,b),d}function N(a,b){var c=c===void 0?!1:c;Object.isExtensible(a);a=xb(a.g,b);a=a!==null?a:void 0;a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}
function O(a,b,c){if(c!=null&&typeof c!=="boolean")throw Error("Expected boolean but got "+Aa(c)+": "+c);vb(a);var e=a.g;yb(e,e[G]|0,b,c===!1?void 0:c);return a};function P(a,b,c){this.g=pb(a,b,c)}P.prototype.toJSON=function(){var a=ob(this);return a};P.prototype[F]=I;P.prototype.toString=function(){return this.g.toString()};var Ab=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};function Q(){this.l=this.l;this.o=this.o}Q.prototype.l=!1;Q.prototype.isDisposed=function(){return this.l};Q.prototype.dispose=function(){this.l||(this.l=!0,this.G())};Q.prototype[Symbol.dispose]=function(){this.dispose()};Q.prototype.G=function(){if(this.o)for(;this.o.length;)this.o.shift()()};var Bb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Cb(a,b){for(var c,e,d=1;d<arguments.length;d++){e=arguments[d];for(c in e)a[c]=e[c];for(var h=0;h<Bb.length;h++)c=Bb[h],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var Db=globalThis.trustedTypes,Eb;function Fb(){var a=null;if(!Db)return a;try{var b=function(c){return c};a=Db.createPolicy("uf-api#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function Gb(a){this.g=a}Gb.prototype.toString=function(){return this.g+""};function Hb(a){var b;Eb===void 0&&(Eb=Fb());a=(b=Eb)?b.createScriptURL(a):a;return new Gb(a)};var Ib=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Jb(a,b){b=Ib.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)}function Kb(a){a=a===void 0?document:a;var b,c;a=(c=(b=a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};function Lb(a,b){if(b instanceof Gb)b=b.g;else throw Error("");a.src=b;(b=Kb(a.ownerDocument))&&a.setAttribute("nonce",b)};function Mb(a){var b=va.apply(1,arguments);if(b.length===0)return Hb(a[0]);for(var c=a[0],e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return Hb(c)};function Nb(a,b,c){function e(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(var d=1;d<c.length;d++){var h=c[d];if(!Ba(h)||E(h)&&h.nodeType>0)e(h);else{a:{if(h&&typeof h.length=="number"){if(E(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}La(f?Na(h):h,e)}}}function Ob(a){var b="SCRIPT";a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function Pb(a){this.g=a||D.document||document}Pb.prototype.append=function(a,b){Nb(a.nodeType==9?a:a.ownerDocument||a.document,a,arguments)};function Qb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var Rb="closure_listenable_"+(Math.random()*1E6|0);var Sb=0;function Tb(a,b,c,e,d){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!e;this.M=d;this.key=++Sb;this.K=this.L=!1}function R(a){a.K=!0;a.listener=null;a.proxy=null;a.src=null;a.M=null};function Ub(a){this.src=a;this.g={};this.h=0}Ub.prototype.add=function(a,b,c,e,d){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var f=Vb(a,b,e,d);f>-1?(b=a[f],c||(b.L=!1)):(b=new Tb(b,this.src,h,!!e,d),b.L=c,a.push(b));return b};function Wb(a,b){var c=b.type;c in a.g&&Ma(a.g[c],b)&&(R(b),a.g[c].length==0&&(delete a.g[c],a.h--))}function Vb(a,b,c,e){for(var d=0;d<a.length;++d){var h=a[d];if(!h.K&&h.listener==b&&h.capture==!!c&&h.M==e)return d}return-1};var Xb="closure_lm_"+(Math.random()*1E6|0),Yb={},Zb=0;
function $b(a,b,c,e,d){if(Array.isArray(b))for(var h=0;h<b.length;h++)$b(a,b[h],c,e,d);else(e=E(e)?!!e.capture:!!e,c=ac(c),a&&a[Rb])?(a=a.i,b=String(b).toString(),b in a.g&&(h=a.g[b],c=Vb(h,c,e,d),c>-1&&(R(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.g[b],a.h--)))):a&&(a=bc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Vb(b,c,e,d)),(c=a>-1?b[a]:null)&&typeof c!=="number"&&c&&!c.K&&((d=c.src)&&d[Rb]?Wb(d.i,c):(e=c.type,b=c.proxy,d.removeEventListener?d.removeEventListener(e,b,c.capture):
d.detachEvent?d.detachEvent(e in Yb?Yb[e]:Yb[e]="on"+e,b):d.addListener&&d.removeListener&&d.removeListener(b),Zb--,(e=bc(d))?(Wb(e,c),e.h==0&&(e.src=null,d[Xb]=null)):R(c))))}function bc(a){a=a[Xb];return a instanceof Ub?a:null}var cc="__closure_events_fn_"+(Math.random()*1E9>>>0);function ac(a){if(typeof a==="function")return a;a[cc]||(a[cc]=function(b){return a.handleEvent(b)});return a[cc]};function S(){Q.call(this);this.i=new Ub(this);this.P=this;this.C=null}Fa(S,Q);S.prototype[Rb]=!0;S.prototype.removeEventListener=function(a,b,c,e){$b(this,a,b,c,e)};
function T(a,b){var c=a.C;if(c){var e=[];for(var d=1;c;c=c.C)e.push(c),++d}a=a.P;c=b.type||b;typeof b==="string"?b=new Qb(b,a):b instanceof Qb?b.target=b.target||a:(d=b,b=new Qb(c,a),Cb(b,d));d=!0;var h;if(e)for(h=e.length-1;h>=0;h--){var f=b.g=e[h];d=U(f,c,!0,b)&&d}f=b.g=a;d=U(f,c,!0,b)&&d;d=U(f,c,!1,b)&&d;if(e)for(h=0;h<e.length;h++)f=b.g=e[h],d=U(f,c,!1,b)&&d}
S.prototype.G=function(){S.N.G.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var e=a.g[c],d=0;d<e.length;d++)++b,R(e[d]);delete a.g[c];a.h--}}this.C=null};function U(a,b,c,e){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var d=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.K&&f.capture==c){var g=f.listener,k=f.M||f.src;f.L&&Wb(a.i,f);d=g.call(k,e)!==!1&&d}}return d&&!e.defaultPrevented};function dc(a){try{return D.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var ec=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function V(){S.call(this);this.headers=new Map;this.h=!1;this.g=null;this.B="";this.j=this.A=this.m=this.H=!1;this.D=0;this.v=null;this.I="";this.F=!1}Fa(V,S);var fc=/^https?$/i,hc=["POST","PUT"],ic=[];function jc(a,b){var c=new V;ic.push(c);b&&c.i.add("complete",b,!1,void 0,void 0);c.i.add("ready",c.R,!0,void 0,void 0);c.D=2E3;c.F=!0;kc(c,a)}p=V.prototype;p.R=function(){this.dispose();Ma(ic,this)};
function kc(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.B+"; newUri="+b);a.B=b;a.H=!1;a.h=!0;a.g=new XMLHttpRequest;a.g.onreadystatechange=Ab(Ea(a.O,a));try{a.A=!0,a.g.open("GET",String(b),!0),a.A=!1}catch(h){lc(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var e in c)b.set(e,c[e]);else if(typeof c.keys==="function"&&typeof c.get==="function"){e=v(c.keys());for(var d=e.next();!d.done;d=e.next())d=d.value,b.set(d,
c.get(d))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(h){return"content-type"==h.toLowerCase()});e=D.FormData&&!1;!(Ka(hc,"GET")>=0)||c||e||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=v(b);for(c=b.next();!c.done;c=b.next())e=v(c.value),c=e.next().value,e=e.next().value,a.g.setRequestHeader(c,e);a.I&&(a.g.responseType=a.I);"withCredentials"in a.g&&a.g.withCredentials!==a.F&&(a.g.withCredentials=a.F);try{mc(a),
a.D>0&&(a.v=setTimeout(a.W.bind(a),a.D)),a.m=!0,a.g.send(""),a.m=!1}catch(h){lc(a)}}p.W=function(){typeof xa!="undefined"&&this.g&&(T(this,"timeout"),this.abort(8))};function lc(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);nc(a);W(a)}function nc(a){a.H||(a.H=!0,T(a,"complete"),T(a,"error"))}p.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,T(this,"complete"),T(this,"abort"),W(this))};
p.G=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),W(this,!0));V.N.G.call(this)};p.O=function(){this.isDisposed()||(this.A||this.m||this.j?oc(this):this.V())};p.V=function(){oc(this)};
function oc(a){if(a.h&&typeof xa!="undefined")if(a.m&&(a.g?a.g.readyState:0)==4)setTimeout(a.O.bind(a),0);else if(T(a,"readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{try{var b=(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(f){b=-1}a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var e;if(!(e=c)){var d;if(d=b===0){var h=String(a.B).match(ec)[1]||null;!h&&D.self&&D.self.location&&(h=D.self.location.protocol.slice(0,-1));d=!fc.test(h?h.toLowerCase():
"")}e=d}e?(T(a,"complete"),T(a,"success")):nc(a)}finally{W(a)}}}function W(a,b){if(a.g){mc(a);var c=a.g;a.g=null;b||T(a,"ready");try{c.onreadystatechange=null}catch(e){}}}function mc(a){a.v&&(clearTimeout(a.v),a.v=null)}p.isActive=function(){return!!this.g};function M(a){this.g=pb(a)}ka(M,P);p=M.prototype;p.getEnableSsEngine=function(){return N(this,2)};p.getEnableAwr=function(){return N(this,3)};p.getAlohaAutoGaRollout=function(){return N(this,5)};p.getEnableConfigurator=function(){return N(this,6)};p.getEnableMweb=function(){return N(this,7)};p.getEnableCtlConsentCheckbox=function(){return N(this,8)};p.getEnableIframe=function(){return N(this,9)};function pc(){var a=new M;a=O(a,5,!0);a=O(a,2,!0);a=O(a,4,!1);a=O(a,8,!0);return O(a,9,!0)}
p.getEnableScreenshotNudge=function(){return N(this,10)};p.getEnableWebStartupConfigEndpoint=function(){return N(this,11)};p.getEnableJunkNudge=function(){return N(this,12)};p.getEnableConfiguratorLocale=function(){return N(this,13)};p.getEnableTinyNoPointer=function(){return N(this,14)};p.getEnableSupportSessionLogging=function(){return N(this,15)};p.getEnableFileUploadForScreenshot=function(){return N(this,16)};p.getEnableDirectDeflectionForSingleCategory=function(){return N(this,17)};
p.getEnableImageSanitization=function(){return N(this,18)};p.getEnableAlohaBinarySplit=function(){return N(this,19)};p.getEnableDbFeedbackIntents=function(){return N(this,20)};p.getEnableMarkMandatoryFieldsWithRequired=function(){return N(this,21)};p.getEnableFeedbackCategoryCustomUi=function(){return N(this,22)};p.getEnableRealtimeCtl=function(){return N(this,23)};function X(a){this.g=pb(a)}ka(X,P);function qc(a){return rc.some(function(b){return b.test(a)})}var rc=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var sc="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");var tc=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),uc=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
function vc(a,b){var c;var e=(c=a.formContent)==null?void 0:c.locale;c=e==null?void 0:e.split("-")[0];e=e&&sc.includes(e)?e:c&&sc.includes(c)?c:void 0;e=(e!=null?e:"en").replaceAll("-","_").toLowerCase();var d;a=((d=a.initializationData)==null?0:d.useNightlyRelease)?"nightly":"live";var h;return(b==null?0:(h=b.getEnableAlohaBinarySplit)==null?0:h.call(b))?Mb(tc,a):Mb(uc,a,e)};var wc,xc,yc,zc;function Ac(a,b,c,e){if(wc&&yc===b)return wc;yc=b;var d=vc(a,e);return wc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Ob(document);Lb(g,d);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+d.toString()))};c.body.appendChild(g)})}
function Bc(a,b,c,e){if(xc&&zc===b)return xc;zc=b;var d=vc(a,e);return xc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=Ob(document);Lb(g,d);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+d.toString()))};c.body.appendChild(g)})}
function Cc(a,b,c,e,d){d=d===void 0?!0:d;var h,f,g,k,l;return B(function(m){switch(m.g){case 1:return h=Date.now(),y(m,Ac(a,c,e,b),2);case 2:f=m.i;if(!(d||((k=a.initializationData)==null?0:k.useNightlyRelease)||((l=a.initializationData)==null?0:l.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);m.g=3;break}return y(m,f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=m.i;case 3:return g.initiateAloha(),m.return(g)}})}
function Dc(a,b,c,e){var d,h,f;return B(function(g){if(g.g==1)return d=Date.now(),y(g,Bc(a,c,e.document,b),2);if(g.g!=3)return h=g.i,y(g,h.initializeFeedbackClientAsync(a,d,b,e),3);f=g.i;f.initiateAloha();return g.return(f)})}
function Ec(a,b,c){var e=!0;e=e===void 0?!0:e;var d,h,f,g,k,l,m,n,q,x;return B(function(z){d=c||D;if((h=b)==null?0:(g=(f=h).getEnableAlohaBinarySplit)==null?0:g.call(f)){k=d;if(k.isFormOpened)throw l=Error("Form is either loading or already opened"),l.name="DuplicateFormError",l;k.isFormOpened=!0;a.callbacks=a.callbacks||{};m=a.callbacks.onClose||function(){};a.callbacks.onClose=function(w){k.isFormOpened=!1;m(w)};try{return z.return(Dc(a,b,k,d))}catch(w){throw k.isFormOpened=!1,w;}}else{n=d;if(n.isFormOpened)throw q=
Error("Form is either loading or already opened"),q.name="DuplicateFormError",q;n.isFormOpened=!0;a.callbacks=a.callbacks||{};x=a.callbacks.onClose||function(){};a.callbacks.onClose=function(w){n.isFormOpened=!1;x(w)};try{return z.return(Cc(a,b,n,d.document,e))}catch(w){throw n.isFormOpened=!1,w;}}z.g=0})};function Fc(a,b){return B(function(c){return c.return(new Promise(function(e){var d=Gc(b!=null?b:"")+"/aloha_form_properties?productId="+a;jc(d,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.g){var l=f.g.responseText;l.indexOf(")]}'\n")==0&&(l=l.substring(5));b:{if(D.JSON)try{var m=D.JSON.parse(l);break b}catch(x){}m=dc(l)}}else m=void 0;var n=k.call(g,m);if(n==null||n=="")h=new X;else{var q=JSON.parse(n);if(!Array.isArray(q))throw Error("dnarr");hb(q,32);h=new X(q)}}catch(x){k=
new X;m=pc();m=O(m,7,!0);m=O(m,10,!0);m=O(m,12,!0);m=O(m,13,!1);m=O(m,14,!0);m=O(m,15,!0);m=O(m,20,!1);n=M;if(m!=null){if(!(m instanceof n))throw Error("Expected instanceof "+jb(n)+" but got "+(m&&jb(m.constructor)));}else m=void 0;n=m;vb(k);q=k.g;yb(q,q[G]|0,1,n);m&&!J(m)&&wb(k.g);h=k}e(h)})}))})}function Gc(a){return qc(a)?a:"https://www.google.com/tools/feedback"};function Hc(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||D,d=e.document,h=a.nonce||Kb(e.document);h&&!a.nonce&&(a.nonce=h);if(a.flow=="help"){var f=za("document.location.href",e);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var g=JSON.stringify(b);(f=g.length<=1200)&&(a.psdJson=g)}f||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=e.GOOGLE_FEEDBACK_START)f.apply(e,
b);else{e=c+"/load.js?";for(var k in a)b=a[k],b==null||E(b)||(e+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=d?new Pb(d.nodeType==9?d:d.ownerDocument||d.document):Ga||(Ga=new Pb);a=Ob(a.g);h&&a.setAttribute("nonce",h);h=Hb(e);Lb(a,h);d.body.appendChild(a)}}
function Ic(a,b,c,e){var d,h;B(function(f){d=c||D;var g=a.serverEnvironment==="DEV",k=c||D;k=a.nonce||Kb(k.document);g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,ma:void 0,defaultFormInputValues:void 0,
defaultFormInputValuesString:void 0,abuseLink:a.abuseLink,additionalDataConsent:a.additionalDataConsent},initializationData:{isLocalServer:g,nonce:k,useNightlyRelease:g,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(k=new Map(Object.entries(b)),g.extraData.productSpecificData=k);h=g;return y(f,Ec(h,e,d),0)})}
function Jc(a,b,c){try{if(a.flow==="help"){var e=a.helpCenterPath.replace(/^\//,"");Jb(c||window,"https://support.google.com/"+e)}else a.flow==="submit"?Hc(a,b,c):Fc(a.productId,a.feedbackServerUri).then(function(d){var h=d.g,f=h[G]|0,g=zb(h,f);if(g!=null&&(f=h[G]|0,!J(d,f))){var k=g;var l=k.g,m=l[G]|0;k=J(k,m)?sb(k,l,m)?tb(k,l,!0):new k.constructor(L(l,m,!1)):k;k!==g&&(ub(d)&&(h=d.g,f=h[G]|0),g=k,f=yb(h,f,1,g),wb(h,f))}d=g;h=!Oa||(d==null?void 0:d.getEnableMweb());f=!a.tinyNoPointer||(d==null?void 0:
d.getEnableTinyNoPointer());!d||d.getAlohaAutoGaRollout()&&h&&f?Ic(a,b,c,d):Hc(a,b,c)},function(d){d&&d.name!=="DuplicateFormError"&&Hc(a,b,c)})}catch(d){Ic(a,b,c,null)}}for(var Kc=["userfeedback","api","startFeedback"],Y=D,Z;Kc.length&&(Z=Kc.shift());)Kc.length||Jc===void 0?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Jc;}).call(this);
